# --- General Settings ---
# Select the feature detector: "GFTT", "SIFT", or "ORB"
feature_detector: "SIFT"

# --- Camera and Pose Estimation ---
camera_downscale_factor: 2
ransac_threshold: 1.0 # RANSAC outlier threshold in pixels

# --- Visualization ---
max_trail_length: 3

# ===================================================================
# --- Detector-Specific Parameters ---
# ===================================================================

gftt:
  max_features: 1000
  quality_level: 0.01
  min_distance: 10.0
  redetection_ratio: 0.9 # Redetect if count drops below max_features * this ratio

sift:
  max_features: 500
  nOctaveLayers: 3
  contrastThreshold: 0.04
  edgeThreshold: 10.0
  sigma: 1.6
  redetection_ratio: 0.8

orb:
  max_features: 1000
  scale_factor: 1.2
  n_levels: 8
  edge_threshold: 31
  WTA_K: 2
  scoreType: 1 # 0 for HARRIS_SCORE, 1 for FAST_SCORE
  patchSize: 31
  redetection_ratio: 0.9